### ISSUE TITLE
Logic for pushing images is incorrect here or in Perma

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/docker-compose-update-action#7]
After the correction of #6, this no longer works to build and push images as used in https://github.com/harvard-lil/perma/blob/6eca0930bd770327dcd215eba0e7ffc3a4528237/.github/workflows/tests.yml#L93-L102 -- I believe that when it compares hashes, the image update commit has already happened, so there's no change.

**Comment by bensteinberg** [comment]
The reason this "worked" previously is that it always built and pushed after a PR was merged.

**Comment by rebeccacremona** [comment]
What if we made another branch for this step to check against? And once it pushes the image to the registry (and succeeds), it updates that branch to match develop?
